### PR TITLE
Use arch_buil and os_build for installer

### PR DESCRIPTION
**Pull request by uilianries**
Related discussion: https://cpplang.slack.com/archives/C41CWV9HA/p1575033208373700

/cc @iancuio

### CODE REVIEW

**Comment by SSE4** [comment]
I guess we should use here `self.info.include_build_settings` as well

**Comment by uilianries** [comment]
@SSE4 Good catch!

**Comment by uilianries** [comment]
@SSE4 Done!

**Comment by SSE4** [comment]
@uilianries it fails on appveyor:
```
C:\projects\conan-mingw-installer-p6wrh\test_package/main.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <iostream>
 ^
```

**Comment by uilianries** [comment]
@SSE4 Fixed! The problem was that the default settings.os was x86_64 and didn't work when os_build was x86 (cross-building x86 to x86_64).

**Pull request merged**
